In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.rand(2,2)
print(x)

tensor([[0.8807, 0.9862],
        [0.6916, 0.8112]])


In [6]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x+y
print(z)


tensor([[1.3699, 1.5075],
        [0.9490, 0.5751]])


In [14]:
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[0,:])

tensor([[0.4936, 0.9426, 0.6243],
        [0.5897, 0.6410, 0.7161],
        [0.0418, 0.3939, 0.5150],
        [0.1945, 0.8786, 0.5371],
        [0.9218, 0.8909, 0.6702]])
tensor([0.4936, 0.5897, 0.0418, 0.1945, 0.9218])
tensor([0.4936, 0.9426, 0.6243])


In [3]:
device = torch.device('cuda')

In [7]:
x = torch.ones(5, device=device)
print(x)
y = torch.ones(5, device=device)
z = x + y
z.cpu().numpy()

tensor([1., 1., 1., 1., 1.], device='cuda:0')


array([2., 2., 2., 2., 2.], dtype=float32)

In [9]:
x1 = torch.ones(5, requires_grad=True)
print(x1)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
